### ISSUE TITLE
Error in events.js when running yo impactplusplus

### ISSUE THREAD

**Issue by jeromecovington** [racingcow/generator-impactplusplus#3]
I'm getting these errors after I enter all of my information (including my ImpactJS key) using the impactplusplus generator.

```
invoke   impactplusplus:update-impactjs
	downloading from http://impactjs.com

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at done (/home/jcovington/.nvm/v0.10.36/lib/node_modules/generator-impactplusplus/node_modules/yeoman-generator/lib/base.js:318:16)
    at /home/jcovington/.nvm/v0.10.36/lib/node_modules/generator-impactplusplus/update-impactjs/index.js:67:17
    at cb (/home/jcovington/.nvm/v0.10.36/lib/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:224:23)
    at onError (/home/jcovington/.nvm/v0.10.36/lib/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:216:12)
    at /home/jcovington/.nvm/v0.10.36/lib/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:65:16
    at Object.oncomplete (fs.js:108:15)
```

**Comment by jeromecovington** [comment]
I tried a couple of different versions of NodeJS (0.10 and 0.12) while running through the Yeoman generator. With both versions of NodeJS, I encountered the same error.

**Comment by racingcow** [comment]
@jeromecovington ,

It doesn't seem to be downloading impactjs for some reason. Is it possible that you are running from a command prompt / bash shell where git is not in the path? 

If you run `git`, on your command prompt, for example, do you see the usage help text or do you get an error?

I get the same error that you do when I try and run `yo impactplusplus` from a machine without git in the path.

**Comment by itsOgden** [comment]
I'm getting almost the exact same error on my end as well. I did verify that git is in the path and working just fine. 

```
invoke   impactplusplus:update-impactjs
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at emit (events.js:87:13)
    at done (/Users/Pdog1/nvm/versions/node/v0.12.0/lib/node_modules/generator-impactplusplus/node_modules/yeoman-generator/lib/base.js:318:16)
    at /Users/Pdog1/nvm/versions/node/v0.12.0/lib/node_modules/generator-impactplusplus/update-impactjs/index.js:67:17
    at cb (/Users/Pdog1/nvm/versions/node/v0.12.0/lib/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:224:23)
    at onError (/Users/Pdog1/nvm/versions/node/v0.12.0/lib/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:216:12)
    at /Users/Pdog1/nvm/versions/node/v0.12.0/lib/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:65:16
    at FSReqWrap.oncomplete (fs.js:99:15)
```

**Comment by racingcow** [comment]
I switched to a Mac (was originally working on Windows) and got the exact same error once. After deleting the files and running the generator again, however, I can't seem to get it to happen again.

I've improved the error handling a bit. @jeromecovington or @itsOgden , could you try it once more with the latest from github, and let me know the output?...

```bash
sudo npm uninstall -g generator-impactplusplus
sudo npm install -g git+https://github.com/racingcow/generator-impactplusplus.git
yo impactplusplus
```

**Comment by itsOgden** [comment]
@racingcow,

this is the error I get now: 
```
impactjs...
   invoke   impactplusplus:update-impactjs
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EACCES, mkdir '/lib'
    at Error (native)
```

**Comment by racingcow** [comment]
Thanks, @itsOgden. I added more logging to try and help track it down. Could you try it once more for me with the latest off of github and post your output?

Here is what I get when I run it...

``` bash
...
? What would you like to call your game? impacttest3
? Enter a description for your game: You should play this game
? What is your github user name? someuser
? Impactjs location? (or license key to download) XXXX-XXXX-XXXX-XXXX
? Start with which sample? supercollider
impactjs...
   invoke   impactplusplus:update-impactjs
    downloading from http://impactjs.com
src = "../impact"
destinationRoot = "/Users/dmiller/Documents/dev/github/impacttest3"
dest = "/Users/dmiller/Documents/dev/github/impacttest3/lib/impact"
creating dest
checking if "../impact/lib/impact" exists.
exists = true
adjSrc = ../impact/lib/impact
rm "../impact"
finished rm
"base" files...
impactplusplus...
    downloading from https://github.com/collinhover/impactplusplus.git
    copying sample "supercollider"
   create package.json
   create bower.json
   create readme.md
   create Gruntfile.js
   create .editorconfig
   create .jshintrc
...
```

Thanks again, and sorry for the slow progress.

**Comment by itsOgden** [comment]
@racingcow, it worked! Dunno what you changed, but it all worked for me this time. 

```
? What would you like to call your game? gutsy
? Enter a description for your game: You should play this game
? What is your github user name? someuser
? Impactjs location? (or license key to download) ****-****-****-****
? Start with which sample? blank
impactjs...
   invoke   impactplusplus:update-impactjs
    downloading from http://impactjs.com
src = "../impact"
destinationRoot = "/Users/Pdog1/dev/gutsy"
dest = "/Users/Pdog1/dev/gutsy/lib/impact"
dest exists. Deleting...
dest deleted
creating dest
checking if "../impact/lib/impact" exists.
exists = true
adjSrc = ../impact/lib/impact
rm "../impact"
finished rm
"base" files...
impactplusplus...
    downloading from https://github.com/collinhover/impactplusplus.git
   create package.json
   create bower.json
   create readme.md
   create Gruntfile.js
   create .editorconfig
   create .jshintrc
```

Thanks so much for your help and for making this, you're awesome!

**Comment by BrandonClapp** [comment]
@racingcow I received the same error.

? What would you like to call your game? Age of Crusade
? Enter a description for your game: Multiplayer browser based building and capture game.
? What is your github user name? BrandonClapp
? Impactjs location? (or license key to download) 1234
? Start with which sample? blank
impactjs...
   invoke   impactplusplus:update-impactjs
events.js:77
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at emit (events.js:77:13)
    at done (/Users/brandon/Documents/Git/scaffold-test/node_modules/generator-impactplusplus/node_modules/yeoman-generator/lib/base.js:318:16)
    at /Users/brandon/Documents/Git/scaffold-test/node_modules/generator-impactplusplus/update-impactjs/index.js:67:17
    at cb (/Users/brandon/Documents/Git/scaffold-test/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:224:23)
    at onError (/Users/brandon/Documents/Git/scaffold-test/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:216:12)
    at /Users/brandon/Documents/Git/scaffold-test/node_modules/generator-impactplusplus/node_modules/ncp/lib/ncp.js:65:16
    at FSReqWrap.oncomplete (fs.js:72:15)
Brandons-MBP:scaffold-test brandon$ 

Upon receiving the error, I find that there is a lib\impact folder containing no files. Running the yo impactplusplus or sudo yo impactplusplus commands subsequent times yields the same result.

**Comment by racingcow** [comment]
@BrandonClapp ,

This will be the slowest response in history, but I just now saw this... Did you happen to remember if you used a valid ImpactJS key with the generator.
